{
 "title": "Storj TV-Dashboard",
 "tags": [
  "storj",
  "storj-tv"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "storj:fleet_min_status" }
   ]
  },
  {
   "title": "ONLINE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(storj_node_up)" }
   ]
  },
  {
   "title": "EARNINGS $",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(storj_payout_current_month_usd)"
    }
   ]
  },
  {
   "title": "DISK %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(storj_disk_used_bytes) / (sum(storj_disk_used_bytes) + sum(storj_disk_available_bytes) + sum(storj_disk_trash_bytes))"
    }
   ]
  },
  {
   "title": "EGRESS LIVE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "sum(storj:egress_rate_5m_bps)" }
   ]
  },
  {
   "title": "Egress / Ingress live",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "sum(storj:egress_rate_5m_bps)", "legendFormat": "Egress" },
    { "expr": "sum(storj:ingress_rate_5m_bps)", "legendFormat": "Ingress" }
   ]
  },
  {
   "title": "Pro Node",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "targets": [
    { "expr": "storj_node_up" },
    { "expr": "storj_payout_current_month_usd" }
   ]
  }
 ]
}